import { NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

export const maxDuration = 60;

export async function POST(request) {
  try {
    const { baseImageUrl, garmentImageUrl } = await request.json();

    if (!baseImageUrl || !garmentImageUrl) {
      return NextResponse.json(
        { success: false, error: 'Base image and garment image are required' },
        { status: 400 }
      );
    }

    console.log('🎨 Starting VTO generation...');

    // Initialize Gemini
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.error('❌ NEXT_PUBLIC_GEMINI_API_KEY is not set!');
      throw new Error('API key not configured');
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-image' });

    // Fetch images
    console.log('📥 Fetching base image...');
    const baseImageResponse = await fetch(baseImageUrl);
    const baseImageBuffer = await baseImageResponse.arrayBuffer();
    const baseImageBase64 = Buffer.from(baseImageBuffer).toString('base64');

    console.log('📥 Fetching garment image...');
    const garmentImageResponse = await fetch(garmentImageUrl);
    const garmentImageBuffer = await garmentImageResponse.arrayBuffer();
    const garmentImageBase64 = Buffer.from(garmentImageBuffer).toString('base64');

    // IMPROVED PROMPT FOR VTO
    const prompt = `You are an expert virtual try-on AI system. Your task is to create a photorealistic image where the EXACT PERSON from the first image (base photo) is wearing the EXACT GARMENT from the second image (garment photo).

CRITICAL REQUIREMENTS - MUST FOLLOW:

1. PERSON PRESERVATION (MOST IMPORTANT):
   - Use the EXACT same person from the base photo - their face, body shape, skin tone, hair, and proportions
   - NEVER generate a different person or model
   - Keep the person's pose and stance from the base photo
   - Maintain all identifying features of the original person

2. GARMENT APPLICATION:
   - Place the garment FROM THE SECOND IMAGE directly onto the person's body
   - The garment MUST appear on the person, not floating or separate
   - Ensure the garment fits the person's body contours naturally
   - Preserve the exact color, pattern, texture, and design of the garment

3. REALISTIC INTEGRATION:
   - Match the garment's lighting to the base photo's lighting conditions
   - Generate realistic shadows where the fabric naturally folds
   - Create natural fabric drape and wrinkles based on body movement
   - Blend the garment edges seamlessly with the person's body
   - Ensure proper perspective and scale

4. FABRIC PHYSICS:
   - Simulate how the fabric would naturally drape on THIS SPECIFIC person's body
   - Add realistic wrinkles at joints (elbows, shoulders, waist)
   - Show fabric tension and compression where appropriate
   - Make sure the garment looks three-dimensional, not flat

5. COLOR AND TEXTURE:
   - Match the garment's colors accurately from the second image
   - Preserve fabric texture (cotton, denim, silk, etc.)
   - Maintain any patterns, logos, or designs exactly as shown
   - Adjust lighting on the garment to match the base photo's environment

6. BODY PARTS:
   - Keep visible body parts (hands, arms, neck) exactly as in the base photo
   - Do not hide or remove any body parts that should be visible
   - Ensure natural transitions between garment and skin

7. BACKGROUND:
   - Keep the EXACT same background from the base photo
   - Do not change or modify the background in any way
   - Maintain the same lighting and environment

OUTPUT: A single, photorealistic image showing the exact person from the first image now wearing the exact garment from the second image, as if they naturally put it on.`;

    console.log('🤖 Calling Gemini 2.5 Flash Image...');

    const result = await model.generateContent({
      contents: [{
        role: 'user',
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: baseImageBase64
            }
          },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: garmentImageBase64
            }
          },
          { text: prompt }
        ]
      }],
      generationConfig: {
        temperature: 0.2, // Lower temperature for more consistent results
        topK: 32,
        topP: 0.95,
      }
    });

    const response = await result.response;
    const generatedImage = response.candidates[0].content.parts[0];

    if (!generatedImage || !generatedImage.inlineData) {
      throw new Error('No image generated by Gemini');
    }

    console.log('✅ VTO image generated successfully');

    return NextResponse.json({
      success: true,
      imageData: generatedImage.inlineData.data,
    });

  } catch (error) {
    console.error('❌ VTO Generation Error:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to generate VTO image' },
      { status: 500 }
    );
  }
}